/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belowwaterapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author RedietBerhe
 */
public class BelowWaterGUI extends javax.swing.JFrame {
     private ArrayList <Company> companies;
     private int fuelamount;
     private int soldamount;
    private int profit;
     
    /**
     * Creates new form BelowWaterGUI
     */
    public BelowWaterGUI() {
        initComponents();
        fuelAmountLBL.setVisible(false);
        fuelamountTF.setVisible(false);
        soldamountTF.setVisible(false);
        soldAmountLBL.setVisible(false);
       
        companies = new ArrayList<>();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profitCalcBTN = new javax.swing.JButton();
        companyNameComboBox = new javax.swing.JComboBox<>();
        companyLBL = new javax.swing.JLabel();
        soldAmountLBL = new javax.swing.JLabel();
        soldamountTF = new javax.swing.JTextField();
        fuelAmountLBL = new javax.swing.JLabel();
        fuelamountTF = new javax.swing.JTextField();
        profitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        profitCalcBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profitCalcBTN.setText("Profit Calculation");
        profitCalcBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitCalcBTNActionPerformed(evt);
            }
        });
        getContentPane().add(profitCalcBTN);
        profitCalcBTN.setBounds(220, 60, 220, 30);

        companyNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mackerel", "Whiting", "Pollack", "Codling" }));
        getContentPane().add(companyNameComboBox);
        companyNameComboBox.setBounds(240, 130, 120, 22);

        companyLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        companyLBL.setForeground(new java.awt.Color(255, 204, 204));
        companyLBL.setText("Company");
        getContentPane().add(companyLBL);
        companyLBL.setBounds(80, 130, 70, 30);

        soldAmountLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        soldAmountLBL.setForeground(new java.awt.Color(255, 204, 204));
        soldAmountLBL.setText("Total amount from sold fish");
        getContentPane().add(soldAmountLBL);
        soldAmountLBL.setBounds(60, 180, 160, 30);

        soldamountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldamountTFActionPerformed(evt);
            }
        });
        getContentPane().add(soldamountTF);
        soldamountTF.setBounds(260, 180, 64, 22);

        fuelAmountLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fuelAmountLBL.setForeground(new java.awt.Color(255, 204, 204));
        fuelAmountLBL.setText("Total amount paid for fuel");
        getContentPane().add(fuelAmountLBL);
        fuelAmountLBL.setBounds(60, 236, 160, 20);
        getContentPane().add(fuelamountTF);
        fuelamountTF.setBounds(260, 230, 80, 22);

        profitBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profitBTN.setText("Profit");
        profitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(profitBTN);
        profitBTN.setBounds(230, 340, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\RedietBerhe\\OneDrive - National College of Ireland\\Documents\\OOP\\BelowWaterApp\\src\\belowwaterapp\\underwater3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, 0, 580, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profitCalcBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitCalcBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitCalcBTNActionPerformed

    private void soldamountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldamountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldamountTFActionPerformed

    private void profitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitBTNActionPerformed
                // TODO add your handling code here:
                soldamount=Integer.parseInt(soldamountTF.getText());
                fuelamount=Integer.parseInt(fuelamountTF.getText());
                
                
                profit=soldamount - fuelamount;
                JOptionPane.showMessageDialog(null,"The profit of this company is :" +profit);
                
                
    }//GEN-LAST:event_profitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BelowWaterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BelowWaterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BelowWaterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BelowWaterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BelowWaterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyLBL;
    private javax.swing.JComboBox<String> companyNameComboBox;
    private javax.swing.JLabel fuelAmountLBL;
    private javax.swing.JTextField fuelamountTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton profitBTN;
    private javax.swing.JButton profitCalcBTN;
    private javax.swing.JLabel soldAmountLBL;
    private javax.swing.JTextField soldamountTF;
    // End of variables declaration//GEN-END:variables
}
