/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belowwaterapp;


import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author RedietBerhe
 */
public class DataGUI extends javax.swing.JFrame {
    private ArrayList<Data> dList;
    private double hour;
    private int totalFish;
    private int caught;
    private int sold;
    private double fuel;
    private String companyName;
    
     
    /**
     * Creates new form DataGUI
     */
    public DataGUI() {
        initComponents();
        dList = new ArrayList<>();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hourLBL = new javax.swing.JLabel();
        fuelTF = new javax.swing.JTextField();
        totalfishLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        totalfishTF = new javax.swing.JTextField();
        caughtTF = new javax.swing.JTextField();
        caughtLBL = new javax.swing.JLabel();
        submitBTN = new javax.swing.JButton();
        soldLBL = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        soldTF = new javax.swing.JTextField();
        hourTF = new javax.swing.JTextField();
        fuelLBL = new javax.swing.JLabel();
        displayBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        hourLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hourLBL.setForeground(new java.awt.Color(255, 0, 102));
        hourLBL.setText("Hours Spent");
        getContentPane().add(hourLBL);
        hourLBL.setBounds(46, 119, 88, 28);

        fuelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTFActionPerformed(evt);
            }
        });
        getContentPane().add(fuelTF);
        fuelTF.setBounds(219, 182, 89, 22);

        totalfishLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalfishLBL.setForeground(new java.awt.Color(255, 0, 102));
        totalfishLBL.setText("Total Fish");
        getContentPane().add(totalfishLBL);
        totalfishLBL.setBounds(46, 227, 102, 30);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLBL.setText("Manage Data");
        getContentPane().add(titleLBL);
        titleLBL.setBounds(221, 6, 141, 34);

        totalfishTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalfishTFActionPerformed(evt);
            }
        });
        getContentPane().add(totalfishTF);
        totalfishTF.setBounds(219, 235, 89, 22);

        caughtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caughtTFActionPerformed(evt);
            }
        });
        getContentPane().add(caughtTF);
        caughtTF.setBounds(212, 275, 89, 22);

        caughtLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caughtLBL.setForeground(new java.awt.Color(255, 0, 153));
        caughtLBL.setText("Caught");
        getContentPane().add(caughtLBL);
        caughtLBL.setBounds(46, 275, 60, 20);

        submitBTN.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        submitBTN.setForeground(new java.awt.Color(255, 0, 51));
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(submitBTN);
        submitBTN.setBounds(155, 353, 107, 33);

        soldLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soldLBL.setForeground(new java.awt.Color(255, 0, 153));
        soldLBL.setText("Sold");
        getContentPane().add(soldLBL);
        soldLBL.setBounds(46, 315, 48, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mackerel", "Whiting", "Pollack", "Codling" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(219, 77, 143, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("Company");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 74, 88, 27);
        getContentPane().add(soldTF);
        soldTF.setBounds(212, 313, 89, 22);

        hourTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourTFActionPerformed(evt);
            }
        });
        getContentPane().add(hourTF);
        hourTF.setBounds(219, 123, 89, 22);

        fuelLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fuelLBL.setForeground(new java.awt.Color(255, 0, 102));
        fuelLBL.setText("Fuel consumed");
        getContentPane().add(fuelLBL);
        fuelLBL.setBounds(46, 177, 102, 30);

        displayBTN.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        displayBTN.setForeground(new java.awt.Color(255, 0, 0));
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN);
        displayBTN.setBounds(280, 353, 101, 33);

        clearBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearBTN.setForeground(new java.awt.Color(255, 0, 0));
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(clearBTN);
        clearBTN.setBounds(399, 355, 95, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\RedietBerhe\\Downloads\\underwater2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fuelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTFActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fuelTFActionPerformed

    private void totalfishTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalfishTFActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_totalfishTFActionPerformed

    private void caughtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caughtTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_caughtTFActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        
        hour= Double.parseDouble(hourTF.getText());
        caught=Integer.parseInt(caughtTF.getText());
        fuel= Integer.parseInt(fuelTF.getText());
        totalFish=Integer.parseInt(totalfishTF.getText());
        sold=Integer.parseInt(soldTF.getText());
       companyName= (String)jComboBox1.getSelectedItem(); 
        
        Data d= new Data();
        
        d.setHour(hour);
        d.setCaught(caught);
        d.setFuel(fuel);
        d.setTotalFish(totalFish);
        d.setSold(sold);
        d.setCompanyName(companyName);
        
        dList.add(d);
        
        
    }//GEN-LAST:event_submitBTNActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void hourTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hourTFActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        for(Data d:dList){
            JOptionPane.showMessageDialog(null,"Company Name:  "+d.getCompanyName()+"  "+"Hours spent:  "+d.getHour()+" " + "Total fish:  "+d.getTotalFish()+"  "+"Caught:  "+d.getCaught()+" "+"Sold:  "+d.getSold()+ "  " +"Fuel consumed:  "+d.getFuel());
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // clears and resets all fields
        hourTF.setText("");
        fuelTF.setText("");
        caughtTF.setText("");
        totalfishTF.setText("");
        soldTF.setText("");
        jComboBox1.setSelectedIndex(0);
        
    }//GEN-LAST:event_clearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caughtLBL;
    private javax.swing.JTextField caughtTF;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JLabel fuelLBL;
    private javax.swing.JTextField fuelTF;
    private javax.swing.JLabel hourLBL;
    private javax.swing.JTextField hourTF;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel soldLBL;
    private javax.swing.JTextField soldTF;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel totalfishLBL;
    private javax.swing.JTextField totalfishTF;
    // End of variables declaration//GEN-END:variables
}
